/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package birthday.greetings;

import org.junit.Test;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class EmployeeFinderTest {
    @Test
    public void should_find_employees_by_birthday() {
        //given
        final LocalDate date = LocalDate.of(2019,2,23);
        //when
        EmployeeFinder employeeFinder = new EmployeeFinder();
        List<Employee> employees = employeeFinder.finder(date);
        //then
        assertThat(employees.get(0).getFirstName()).isEqualTo("ddd");
        assertThat(employees.size()).isEqualTo(1);
    }

    @Test
    public void name() {
    }
}
